include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: true
    sort_constructors_first: true
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    use_key_in_widget_constructors: true
